# INTEL CONFIDENTIAL

# Copyright (C) 2022 Intel Corporation

# This software and the related documents are Intel copyrighted materials, and your use of them is governed by the express
# license under which they were provided to you ("License"). Unless the License provides otherwise, you may not use, modify,
# copy, publish, distribute, disclose or transmit this software or the related documents without Intel's prior written permission.

# This software and the related documents are provided as is, with no express or implied warranties, other than those that are expressly stated in the License.

name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: system-area
    attributes:
      label: Area
      description: What area of the system is believed to be affected?
      options:
        - Kaskey Park
        - Project AIR
        - I am not sure
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: |
        This is where you get to tell us what went wrong. When doing so, please make sure to include *all* relevant information.

        Please try to include:
        * What you were doing when you experienced the bug.
        * Any error messages you saw, *where* you saw them, and what you believe may have caused them (if you have any ideas).
        * When possible, steps to reliably produce the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: |
        This is where you add all the logs related to the bug.
    validations:
      required: true